### ISSUE TITLE
Following up on further tuning for InfluxdDB writes

### ISSUE THREAD

**Issue by filipecosta90** [RedisLabsModules/automata#6]
Following on an error on Influx due to high ingest/cardinality (100K series) and given on this tests we are optimizing for writes I believe we should:
- increase the `cache-max-memory-size` from 1GB to 12GB ( 10% of the specific deployment ). 
- set `max-values-per-tag = 0` ( limit is 100K and we test for larger cardinality )

Further details on docs: https://docs.influxdata.com/influxdb/v1.8/administration/config/

Altered setting within `/etc/influxdb/influxdb.conf`
```
  # CacheMaxMemorySize is the maximum size a shard's cache can
  # reach before it starts rejecting writes.
  # Valid size suffixes are k, m, or g (case insensitive, 1024 = 1k).
  # Values without a size suffix are in bytes.
  cache-max-memory-size = "12g"


 # The maximum number of tag values per tag that are allowed before writes are dropped.  This limit
  # can prevent high cardinality tag values from being written to a measurement.  This limit can be 
  # disabled by setting it to 0.                                                                     
  max-values-per-tag = 0 
  ```

----------------------
Error details:
```
{"error":"partial write: max-values-per-tag limit exceeded (100000/100000): measurement=\"cpu\" tag=\"hostname\" value=\"host_99721\" dropped=279"}
```

**Comment by chayim** [comment]
At righting - this was something that could not be set, it's now a default ansible variable. By default we're using your 12g, but **when** you want to change it for a target host, you can override on the command line with 
```
-e influxdb_default_max_cache_size=somevalue
```
